[package]
name = "my_os"
version = "1.0.0"
authors = ["ag_dubs"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
x86 = "0.8.0"
time = { default-fearures = false, version = "0.1" }
log = { default-features = false, version = "0.3.6" }
spin = "0.4.4"
